// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNC5XFoqZN8XPUNb0QNmASu7K6HoYjrAM',
    appId: '1:281591271361:web:c588517bb70e2de0832940',
    messagingSenderId: '281591271361',
    projectId: 'nutrismart-90204',
    authDomain: 'nutrismart-90204.firebaseapp.com',
    storageBucket: 'nutrismart-90204.firebasestorage.app',
    measurementId: 'G-EE4XQVR8NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAad4-MO9uq4WM2N83HmA-TeD83uRw-ptk',
    appId: '1:281591271361:android:1b9ef664946d5947832940',
    messagingSenderId: '281591271361',
    projectId: 'nutrismart-90204',
    storageBucket: 'nutrismart-90204.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgL5lHBpThntQ6xjOK0NmRHGgyKmCwIUA',
    appId: '1:281591271361:ios:3531f893e58c9156832940',
    messagingSenderId: '281591271361',
    projectId: 'nutrismart-90204',
    storageBucket: 'nutrismart-90204.firebasestorage.app',
    iosClientId: '281591271361-kg1mjmu4hi6g9j933stfk6pumvdqptg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutrismart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgL5lHBpThntQ6xjOK0NmRHGgyKmCwIUA',
    appId: '1:281591271361:ios:3531f893e58c9156832940',
    messagingSenderId: '281591271361',
    projectId: 'nutrismart-90204',
    storageBucket: 'nutrismart-90204.firebasestorage.app',
    iosClientId: '281591271361-kg1mjmu4hi6g9j933stfk6pumvdqptg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutrismart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNC5XFoqZN8XPUNb0QNmASu7K6HoYjrAM',
    appId: '1:281591271361:web:021f40036fbb0938832940',
    messagingSenderId: '281591271361',
    projectId: 'nutrismart-90204',
    authDomain: 'nutrismart-90204.firebaseapp.com',
    storageBucket: 'nutrismart-90204.firebasestorage.app',
    measurementId: 'G-6VYXJJ26B5',
  );
}
